# Generated by Django 3.2.16 on 2023-05-22 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_auto_20230424_2207"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "default_related_name": "posts",
                "ordering": ("-pub_date",),
                "verbose_name": "публикация",
                "verbose_name_plural": "Публикации",
            },
        ),
    ]
