# Generated by Django 3.2.16 on 2023-05-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_auto_20230522_1444"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Изображение"
            ),
        ),
    ]
